server:
  port: 8084
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      min-spare: 5
      max: 50
spring:
  application:
    name: dear-comrade-topic
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/customerdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
      show-sql: true

customer:
  datasource:
    host: localhost
    port: 3306
    database: customerdb
    username: root
    password: root